local hiLinks = require"apply".hiLinks
local highlights = require"apply".highlights

local colors = {
    none = "NONE",
    bg_dark = "#1f2335",
    bg = "#24283b",
    bg_highlight = "#292e42",
    terminal_black = "#414868",
    fg = "#c0caf5",
    fg_dark = "#a9b1d6",
    fg_gutter = "#3b4261",
    dark3 = "#545c7e",
    comment = "#565f89",
    dark5 = "#737aa2",
    blue0 = "#3d59a1",
    blue = "#7aa2f7",
    cyan = "#7dcfff",
    blue1 = "#2ac3de",
    blue2 = "#0db9d7",
    blue5 = "#89ddff",
    blue6 = "#B4F9F8",
    blue7 = "#394b70",
    magenta = "#bb9af7",
    purple = "#9d7cd8",
    orange = "#ff9e64",
    yellow = "#e0af68",
    green = "#9ece6a",
    green1 = "#73daca",
    green2 = "#41a6b5",
    teal = "#1abc9c",
    red = "#f7768e",
    red1 = "#db4b4b",
}

hiLinks({
})

highlights({
    Normal = { bg = "#1F2335" },
    SignColumn = { bg = "#1F2335" },
    VertSplit = { bg = "#1F2335" },
    StatusLineNC = { bg = "#1F2335" },
    javascriptTSPunctBracket = { fg = colors.cyan },
    javascriptTSConditional = { fg = colors.cyan},
    javascriptTSConstructor = { fg = colors.blue},
    javascriptTSVariable = { fg = colors.magenta },
    TSTag = { fg = colors.red },
    TSTagDelimiter = { fg = colors.dark3},
    TSType = { fg = colors.blue },
    tsxTSTagAttribute = { fg = colors.magenta },
    rubyTSSymbol = { fg = colors.green },
    rubyTSLabel = { fg = colors.fg },
    rubyTSPunctBracket = { fg = colors.cyan },
    BufferCurrent = { fg = colors.fg, bg = colors.bg_highlight, gui = "bold,italic", guisp = colors.blue},
    BufferCurrentIndex = { fg = colors.terminal_black, bg = colors.bg_highlight},
    BufferCurrentIcon = {bg = colors.bg_highlight},
    BufferCurrentSign = {fg = colors.bg_highlight, bg = colors.bg_highlight},
    BufferCurrentTarget = {bg = colors.bg},
    BufferCurrentMod = {fg = colors.fg, bg = colors.bg_highlight, gui = "bold,italic"},
    BufferIconSeparator = {fg = colors.bg},
    BufferInactive = { fg = colors.dark3, bg = colors.bg, gui = "bold,italic"},
    BufferInactiveIcon = {fg = colors.dark3, bg = colors.bg},
    BufferInactiveIndex = {fg = colors.bg, bg = colors.bg},
    BufferInactiveMod = {fg =  colors.dark3, bg = colors.bg, gui = "bold,italic"},
    BufferInactiveSign = {fg = colors.bg, bg = colors.bg},
    BufferTypeSeparator = {fg = colors.bg, bg = colors.bg},
    BufferTabpageFill = {fg = colors.bg, bg = colors.bg},
    BufferTabpages = {fg = colors.bg, bg = colors.bg},
    BufferVisible = {fg = colors.fg, bg = colors.bg_highlight, gui = "bold,italic"},
    BufferVisibleIcon = {fg = colors.bg, bg = colors.bg_highlight},
    BufferVisibleIndex = {fg = colors.bg, bg = colors.bg_highlight}, 
    BufferVisibleMod = {fg = colors.dark3, bg = colors.bg_highlight, gui = "bold,italic"},
    BufferVisibleSign = {fg = colors.bg, bg = colors.bg_highlight},
    BufferVisibleTarget = {fg = colors.bg, bg = colors.bg_highlight},
    IndentBlanklineChar = { fg = colors.bg_highlight },
    IndentBlanklineContextChar = { fg = colors.fg_gutter },
    LspDiagnosticsVirtualTextWarning = { fg = colors.fg_gutter },
    LspDiagnosticsVirtualTextError = { fg = colors.fg_gutter },
    LspDiagnosticsVirtualTextInformation = { fg = colors.fg_gutter },
    LspDiagnosticsVirtualTextHint = { bg = "", fg = colors.fg_gutter },
    LspSagaLightBulb = { bg = "none", fg = colors.yellow},
    StatusLineNC = { bg = colors.bg_dark, fg = colors.bg },
    VertSplit = { bg = "none", fg = colors.bg },
    CursorLineNr = { gui = "bold" },
    NvimTreeFolderIcon = { fg = colors.fg_gutter },
    NvimTreeOpenedFolderName = { fg = colors.blue1 },
    NvimTreeFolderName = { fg = colors.fg_dark, gui = "bold" },
    NvimTreeRootFolder = { bg = colors.bg, fg = colors.dark3 },
    Type = { fg = colors.magenta },
})
