#!/bin/sh

xrdb -merge $HOME/.Xresources
xset b off &

# xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --output eDP-1 --mode 1920x1080 --scale 1x1 --output HDMI-1 --same-as eDP-1 --mode 1920x1080 --scale 1x1

udiskie -NT 2>&1 > /dev/null &

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

## Autostart 
numlockx
remaps
setxkbmap -model abnt -layout us -variant intl
# setxkbmap -model abnt2 -layout br -variant abnt2
setxkbmap -options caps:swapescape

# WM Initialization
exec dbus-launch awesome
# exec bspwm
# exec dbus-launch qtile start
# exec gnome-session
# exec dbus-launch startplasma-x11
