add_newline = false

[line_break]
disabled = true

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[[battery.display]]
threshold = 30
style = "bold red"

[character]
error_symbol = "[](bold red)"
success_symbol = "[➜](bold green)"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = "took [$duration]($style) "

[directory]
truncation_length = 5
format = " [$path]($style) [$lock_symbol]($lock_style)"
style = "bold white"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold cyan"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_status]
modified = "~${count} "
staged = "樂${count} "
renamed = "»${count} "
deleted = "${count} "
format = '([$all_status$ahead_behind]($style))'
style = "bold dimmed white"

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 50
style = "bold dimmed white"
disabled = true

[package]
disabled = true

[time]
disabled = true

[username]
style_user = "bold green"
show_always = false

[aws]
symbol = " "

[ruby]
disabled = false
symbol = " "
style = "bold red"

[lua]
disabled = false
style = "bold purple"

[python]
disabled = true
symbol = " "
format = "[$symbol$version]($style) "
style = "bold cyan"

[nodejs]
disabled = true
format = "via [$symbol$version]($style) "
symbol = " "
style =	"bold cyan"
